pluralnoun1 = input("Enter a plural noun: ")
occupation = input("Enter an occupation: ")
place = input("Enter a place: ")
number = input("Enter a number: ")
adjective1 = input("Enter a adjective: ")
verb1 = input("Enter a place: ")
pluralnoun2 = input("Enter another plural noun: ")
place2 = input("Enter another place: ")
adjective2 = input("Enter another adjective: ")
pluralnoun3 = input("Enter another plural noun: ")
verb2 = input("Enter another verb ending in -ing: ")
pluralnoun4 = input("Enter another plural noun: ")
adjective3 = input("Enter another adjective: ")
noun1 = input("Enter a noun: ")
body1 = input("Enter a part of the body: ")
verb3 = input("Enter another verb: ")
adjective4 = input("Enter another adjective: ")
body2 = input("Enter another part of the body: ")

print("Hello, my fellow " + pluralnoun1) 
print("in 2022, it’s me, George Washington, the first " +occupation)
print("I am writing from the, " +place )
print("where I have been secretly living for the past " +number)
print("years.")
print("I am concerned by the " +adjective1)
print("state of affairs in America these days. It seems that your politicians are more concerned with  " +verb1)
print ("one another than listening to the " +pluralnoun2)
print ("of the people. When we declared our independence from the " +place2)
print (", we set forth on a/an " +adjective2 )
print ("path guided by the voice of the every day " +pluralnoun3) 
print (".If we’re going to keep " +verb2)
print (", then we need to learn how to respect all " +pluralnoun4)
print (".Don’t get me wrong; we had " +adjective3)
print ("problems in my day too. Benjamin Franklin once called me a/an " +noun1)
print ("and kicked me in the " +body1)
print (". But at the end of the day, we were able to " +verb3) 
print ("in harmony. Let us find that " +adjective4)
print ("spirit once again, or else I'm taking my " +body2)
print ("off the quarter!")


print ("Next madlib!")

adjective1 = input("Enter an adjective: ")
adjective2 = input ("Enter another adjective: ")
bird = input ("Enter a type of bird: ")
room = input ("Enter a room ex. living room, bathroom: ")
verb = input ("Enter a verb: ")
name = input ("Enter a name: ")
noun1 = input ("Enter a noun: ")
liquid = input ("Enter a type of liquid: ")
verb2 = input ("Enter another verb: ")
body = input ("Enter a part of the body: ")
pluralnoun1 = input ("Enter a plural noun: ")
verbs3 = input ("Enter another verb: ")
noun2 = input ("Enter another noun: ")

print ("It was a " +adjective1)
print (",cold December day. I woke up to the " +adjective2)
print ("Smell of " +bird)
print ("Roasting in the " +room)
print ("Downstairs. I " +verb)
print ("The dinner. My mom said, “See if " +name)
print ("Needs a fresh " +noun1)
print (".” So I carried a tray of glasses full of "+liquid)
print ("Into the " +verb2)
print ("room. When I got there, I couldn’t believe my " +body)
print ("! There were " +pluralnoun1)
print (" " +verb3)
print ("On the " +noun2)
print ("!")

print ("Next madlib!")

adjective1 = input("Enter an adjective: ")
nationality = input("Enter a nationality: ")
person = input("Enter a person: ")
noun = input("Enter a noun: ")
adjective2 = input("Enter another adjective: ")
noun2 = input("Enter another noun: ")
adjective3 = input("Enter another adjective: ")
adjective4 = input("Enter another adjective: ")
pluralnoun = input("Enter a plural noun: ")
noun3 = input("Enter another noun: ")
number = input("Enter a number: ")
shape = input("Enter a shape: ")
food1 = input("Enter a food: ")
food2 = input("Enter another food: ")
number2 = input("Enter another number: ")


print ("Pizza was invented by a " +adjective1)
print (" " +nationality)
print ("chef named " +person)
print (". To make pizza, you need to take a lump of " +noun)
print (", and make a thing, round " +adjective2)
print (+noun2)
print (". Then you cover it with " +adjective3)
print ("sauce, " +adjective4)
print ("cheese, and fresh chopped " +pluralnoun)
print (". Next you have to bake it in a very hot " +noun3)
print (". When is it done, cut it into " +number)
print (" "+shape)
print (". Some kids like " +food1)
print ("pizza the best, but my favorite is the " +food2)
print ("pizza. If I could, I would eat pizza " +number2)
print ("times a day!")


print ("Next madlib!")

person1 = input("Enter a person: ")
adjective1 = input("Enter an adjective: ")
adjective2("Enter another adjective: ")
noun1 = input("Enter a noun: ")
adjective3 = input("Enter another adjective: ")
noun2 = input("Enter another noun: ")
adjective4 = input("Enter another adjective: ")
adjective5 = input("Enter another adjective: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter another verb: ")
person2 = input("Enter another person: ")
verb3 = input("Enter another verb: ")
adjective6 = input("Enter another adjective: ")
verb4 = input("Enter another verb: ")


print ("Yesterday, " +person1)
print ("and I went to the park. On our way to the ") +adjective1
print ("park, we saw a " +adjective2)
print (" "+noun1)
print ("on a bike. We also saw big " +adjective3)
print ("balloons tied to a " +noun2)
print (". Once we got to the " +adjective4)
print ("park, the sky turned " +adjective5)
print (". It started to " +verb1)
print ("and " +verb2)
print (". " +person2)
print ("and I " +verb3)
print ("all the way home. Tomorrow we will try to go to the " +adjective6)
print ("Park again and hope it doesn’t " +verb4)
print (".")
